/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrOperaciones;
import controlador.Servicios;
import java.math.BigDecimal;
import java.math.RoundingMode;
import modelo.Estimacion;

/**
 *
 * @author Darwin
 */
public class AgregarFrame extends javax.swing.JFrame {

    //public static Proyecto py = new Proyecto();
    public int[] compAlta = new int[5];
    public int[] compMedia = new int[5];
    public int[] compBaja = new int[5];
    public Estimacion esti;
    
    BigDecimal bigDecimal;
    
    public AgregarFrame() {
        initComponents();
        jPanel1.setBackground(PrincipalFrame.color1);
        this.getContentPane().setBackground(PrincipalFrame.color2);
        this.setResizable(false);
        txtLineasPF.setEditable(false);
        txtMessage.setEditable(false);
        txtLineasPF.setText(String.valueOf(CtrOperaciones.lenguaje));
        lbPfTotal.setText(String.valueOf(CtrOperaciones.est.getPuntoFuncion()));
        bigDecimal = new BigDecimal(CtrOperaciones.est.getLineasCod() * 1000).setScale(2, RoundingMode.UP);
        lbLineasTotal.setText(String.valueOf(bigDecimal));
        
    }

    /**
     * Creates new form AgregarFrame
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnEBaja = new javax.swing.JSpinner();
        spnSeBaja = new javax.swing.JSpinner();
        spnCeBaja = new javax.swing.JSpinner();
        spnAliBaja = new javax.swing.JSpinner();
        spnAieBaja = new javax.swing.JSpinner();
        spnEMedia = new javax.swing.JSpinner();
        spnSeMedia = new javax.swing.JSpinner();
        spnCeMedia = new javax.swing.JSpinner();
        spnAliMedia = new javax.swing.JSpinner();
        spnAieMedia = new javax.swing.JSpinner();
        spnEAlta = new javax.swing.JSpinner();
        spnSeAlta = new javax.swing.JSpinner();
        spnCeAlta = new javax.swing.JSpinner();
        spnAliAlta = new javax.swing.JSpinner();
        spnAieAlta = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnprueba = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbnLenguaje = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lbMessagePF = new javax.swing.JLabel();
        lbMessageL = new javax.swing.JLabel();
        lbPfTotal = new javax.swing.JLabel();
        lbLineasTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMessage = new javax.swing.JTextField();
        txtLineasPF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Entradas Externas (EE)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Salidas Externas (ES)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Consultas Externas (CE)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Archivos Lógicos Internos (ALI)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Archivos de Interfaz Externa (AIE)");

        spnEBaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnEBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnSeBaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnSeBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCeBaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnCeBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAliBaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnAliBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAieBaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnAieBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnEMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnEMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnSeMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnSeMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCeMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnCeMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAliMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnAliMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAieMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnAieMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnEAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnEAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnSeAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnSeAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCeAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnCeAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAliAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnAliAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAieAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnAieAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Baja");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Media");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Alta");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Complejidad");

        btnprueba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnprueba.setText("calcular");
        btnprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpruebaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Lenguaje");

        cbnLenguaje.setBackground(new java.awt.Color(246, 248, 250));
        cbnLenguaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbnLenguaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "JAVA", "PHP", "NODE.JS" }));
        cbnLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnLenguajeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Lineas/PF");

        lbMessagePF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessagePF.setText("Total valor Punto Función: ");

        lbMessageL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessageL.setText("Total valor Lineas Codigo: ");

        lbPfTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPfTotal.setText("jLabel16");

        lbLineasTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLineasTotal.setText("jLabel17");

        txtMessage.setBackground(new java.awt.Color(36, 41, 46));
        txtMessage.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        txtMessage.setForeground(new java.awt.Color(204, 204, 204));
        txtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMessage.setText("PUNTO FUNCIÓN");
        txtMessage.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        txtLineasPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMessageL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbLineasTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbMessagePF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbPfTotal)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbnLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12)
                                .addGap(35, 35, 35)
                                .addComponent(txtLineasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(spnAliBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnAieBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnEBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnSeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(spnAliMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnAieMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnEMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnSeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(spnAliAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnAieAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnEAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnSeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnprueba)
                                .addGap(28, 28, 28)
                                .addComponent(btnOk)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(75, 75, 75))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbnLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtLineasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnEAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnSeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnCeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnAliMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAliAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnAieMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAieAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(spnEBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(spnSeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnCeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnAliBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnAieBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessagePF)
                    .addComponent(lbPfTotal))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessageL)
                    .addComponent(lbLineasTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprueba)
                    .addComponent(btnOk))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        super.dispose();

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpruebaActionPerformed
        // TODO add your handling code here:
         Servicios sv = new Servicios();
         
         
        compAlta[0] = (Integer) spnEAlta.getValue();
        compAlta[1] = (Integer) spnSeAlta.getValue();
        compAlta[2] = (Integer) spnCeAlta.getValue();
        compAlta[3] = (Integer) spnAliAlta.getValue();
        compAlta[4] = (Integer) spnAieAlta.getValue();

        compMedia[0] = (Integer) spnEMedia.getValue();
        compMedia[1] = (Integer) spnSeMedia.getValue();
        compMedia[2] = (Integer) spnCeMedia.getValue();
        compMedia[3] = (Integer) spnAliMedia.getValue();
        compMedia[4] = (Integer) spnAieMedia.getValue();

        compBaja[0] = (Integer) spnEBaja.getValue();
        compBaja[1] = (Integer) spnSeBaja.getValue();
        compBaja[2] = (Integer) spnCeBaja.getValue();
        compBaja[3] = (Integer) spnAliBaja.getValue();
        compBaja[4] = (Integer) spnAieBaja.getValue();
        sv.calcularComplejidad(compBaja, compAlta, compMedia);
        int valor = sv.calcularPf(CtrOperaciones.py.getComponente());
        System.out.println("Valor PF " + valor);
        
        double est = sv.calcularLineasCod();
        System.out.println("Valor LineasCod " + est*1000);

        lbPfTotal.setText(String.valueOf(valor));
        bigDecimal = new BigDecimal(est*1000).setScale(2, RoundingMode.UP);
        lbLineasTotal.setText(String.valueOf(bigDecimal));
 
    }//GEN-LAST:event_btnpruebaActionPerformed

    private void cbnLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnLenguajeActionPerformed
        // TODO add your handling code here:
        if (cbnLenguaje.getSelectedItem() == "JAVA") {
            txtLineasPF.setText("53");
            CtrOperaciones.lenguaje = 53;
        }
        if (cbnLenguaje.getSelectedItem() == "PHP") {
            txtLineasPF.setText("23");
            CtrOperaciones.lenguaje = 23;
        }
        if (cbnLenguaje.getSelectedItem() == "NODE.JS") {
            txtLineasPF.setText("45");
            CtrOperaciones.lenguaje = 45;
        }
        if (cbnLenguaje.getSelectedItem() == "SELECCIONAR") {
            txtLineasPF.setText("53");
            CtrOperaciones.lenguaje = 53;
        }

    }//GEN-LAST:event_cbnLenguajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnprueba;
    private javax.swing.JComboBox<String> cbnLenguaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLineasTotal;
    private javax.swing.JLabel lbMessageL;
    private javax.swing.JLabel lbMessagePF;
    private javax.swing.JLabel lbPfTotal;
    private javax.swing.JSpinner spnAieAlta;
    private javax.swing.JSpinner spnAieBaja;
    private javax.swing.JSpinner spnAieMedia;
    private javax.swing.JSpinner spnAliAlta;
    private javax.swing.JSpinner spnAliBaja;
    private javax.swing.JSpinner spnAliMedia;
    private javax.swing.JSpinner spnCeAlta;
    private javax.swing.JSpinner spnCeBaja;
    private javax.swing.JSpinner spnCeMedia;
    private javax.swing.JSpinner spnEAlta;
    private javax.swing.JSpinner spnEBaja;
    private javax.swing.JSpinner spnEMedia;
    private javax.swing.JSpinner spnSeAlta;
    private javax.swing.JSpinner spnSeBaja;
    private javax.swing.JSpinner spnSeMedia;
    private javax.swing.JTextField txtLineasPF;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
