/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrOperaciones;
import controlador.Servicios;
import javax.swing.JFrame;

/**
 *
 * @author Darwin
 */
public class AgregarFrame extends javax.swing.JFrame {

    //public static Proyecto py = new Proyecto();
    public int[] compAlta = new int[5];
    public int[] compMedia = new int[5];
    public int[] compBaja = new int[5];

    public AgregarFrame() {
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        txtLineasPF.setEditable(false);
        txtMessage.setEditable(false);
        txtLineasPF.setText(String.valueOf(CtrOperaciones.lenguaje));
        lbPfTotal.setText(String.valueOf(CtrOperaciones.est.getPuntoFuncion()));
        lbLineasTotal.setText(String.valueOf(CtrOperaciones.est.getLineasCod()));
        
    }

    /**
     * Creates new form AgregarFrame
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnEBaja = new javax.swing.JSpinner();
        spnSeBaja = new javax.swing.JSpinner();
        spnCeBaja = new javax.swing.JSpinner();
        spnAliBaja = new javax.swing.JSpinner();
        spnAieBaja = new javax.swing.JSpinner();
        spnEMedia = new javax.swing.JSpinner();
        spnSeMedia = new javax.swing.JSpinner();
        spnCeMedia = new javax.swing.JSpinner();
        spnAliMedia = new javax.swing.JSpinner();
        spnAieMedia = new javax.swing.JSpinner();
        spnEAlta = new javax.swing.JSpinner();
        spnSeAlta = new javax.swing.JSpinner();
        spnCeAlta = new javax.swing.JSpinner();
        spnAliAlta = new javax.swing.JSpinner();
        spnAieAlta = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnprueba = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbnLenguaje = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lbMessagePF = new javax.swing.JLabel();
        lbMessageL = new javax.swing.JLabel();
        lbPfTotal = new javax.swing.JLabel();
        lbLineasTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtLineasPF = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Entradas Externas (EE)");

        jLabel2.setText("Salidas Externas (ES)");

        jLabel3.setText("Consultas Externas (CE)");

        jLabel4.setText("Archivos Lógicos Internos (ALI)");

        jLabel5.setText("Archivos de Interfaz Externa (AIE)");

        spnEBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnSeBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCeBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAliBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAieBaja.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnEMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnSeMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCeMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAliMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAieMedia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnEAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnSeAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCeAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAliAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnAieAlta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel6.setText("Baja");

        jLabel7.setText("Media");

        jLabel8.setText("Alta");

        jLabel9.setText("Complejidad");

        btnprueba.setText("calcular");
        btnprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpruebaActionPerformed(evt);
            }
        });

        jLabel11.setText("Lenguaje");

        cbnLenguaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "JAVA", "PHP", "NODE.JS" }));
        cbnLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnLenguajeActionPerformed(evt);
            }
        });

        jLabel12.setText("Lineas/PF");

        lbMessagePF.setText("Total valor Punto Función: ");

        lbMessageL.setText("Total valor Lineas Codigo: ");

        lbPfTotal.setText("jLabel16");

        lbLineasTotal.setText("jLabel17");

        btnCancelar.setText("Cancelar");

        txtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMessage.setText("PUNTO FUNCIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbMessageL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbLineasTotal))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbMessagePF)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbPfTotal)))
                                    .addGap(24, 24, 24))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(spnAliBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnAieBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnEBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnSeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnCeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(spnAliMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnAieMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnEMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnSeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnCeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(spnAliAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnAieAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnEAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnSeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnCeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnprueba)
                                    .addGap(11, 11, 11)
                                    .addComponent(btnOk)
                                    .addGap(13, 13, 13)
                                    .addComponent(btnCancelar))))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbnLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGap(14, 14, 14)
                        .addComponent(txtLineasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbnLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(txtLineasPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnEAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnSeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnCeMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnCeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnAliMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAliAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnAieMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAieAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(spnEBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(spnSeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnCeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnAliBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnAieBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessagePF)
                    .addComponent(lbPfTotal))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMessageL)
                    .addComponent(lbLineasTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprueba)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:

        super.dispose();

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpruebaActionPerformed
        // TODO add your handling code here:
         Servicios sv = new Servicios();

        compAlta[0] = (Integer) spnEAlta.getValue();
        compAlta[1] = (Integer) spnSeAlta.getValue();
        compAlta[2] = (Integer) spnCeAlta.getValue();
        compAlta[3] = (Integer) spnAliAlta.getValue();
        compAlta[4] = (Integer) spnAieAlta.getValue();

        compMedia[0] = (Integer) spnEMedia.getValue();
        compMedia[1] = (Integer) spnSeMedia.getValue();
        compMedia[2] = (Integer) spnCeMedia.getValue();
        compMedia[3] = (Integer) spnAliMedia.getValue();
        compMedia[4] = (Integer) spnAieMedia.getValue();

        compBaja[0] = (Integer) spnEBaja.getValue();
        compBaja[1] = (Integer) spnSeBaja.getValue();
        compBaja[2] = (Integer) spnCeBaja.getValue();
        compBaja[3] = (Integer) spnAliBaja.getValue();
        compBaja[4] = (Integer) spnAieBaja.getValue();
        sv.calcularComplejidad(compBaja, compAlta, compMedia);
        int valor = sv.calcularPf(CtrOperaciones.py.getComponente());
        System.out.println("Valor PF " + valor);
        
        double est = sv.calcularLineasCod();
        System.out.println("Valor LineasCod " + est*1000);

        lbPfTotal.setText(String.valueOf(valor));
        lbLineasTotal.setText(String.valueOf(est*1000));
 
    }//GEN-LAST:event_btnpruebaActionPerformed

    private void cbnLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnLenguajeActionPerformed
        // TODO add your handling code here:
        if (cbnLenguaje.getSelectedItem() == "JAVA") {
            txtLineasPF.setText("53");
            CtrOperaciones.lenguaje = 53;
        }
        if (cbnLenguaje.getSelectedItem() == "PHP") {
            txtLineasPF.setText("23");
            CtrOperaciones.lenguaje = 23;
        }
        if (cbnLenguaje.getSelectedItem() == "NODE.JS") {
            txtLineasPF.setText("45");
            CtrOperaciones.lenguaje = 45;
        }
        if (cbnLenguaje.getSelectedItem() == "SELECCIONAR") {
            txtLineasPF.setText("53");
            CtrOperaciones.lenguaje = 53;
        }

    }//GEN-LAST:event_cbnLenguajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnprueba;
    private javax.swing.JComboBox<String> cbnLenguaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbLineasTotal;
    private javax.swing.JLabel lbMessageL;
    private javax.swing.JLabel lbMessagePF;
    private javax.swing.JLabel lbPfTotal;
    private javax.swing.JSpinner spnAieAlta;
    private javax.swing.JSpinner spnAieBaja;
    private javax.swing.JSpinner spnAieMedia;
    private javax.swing.JSpinner spnAliAlta;
    private javax.swing.JSpinner spnAliBaja;
    private javax.swing.JSpinner spnAliMedia;
    private javax.swing.JSpinner spnCeAlta;
    private javax.swing.JSpinner spnCeBaja;
    private javax.swing.JSpinner spnCeMedia;
    private javax.swing.JSpinner spnEAlta;
    private javax.swing.JSpinner spnEBaja;
    private javax.swing.JSpinner spnEMedia;
    private javax.swing.JSpinner spnSeAlta;
    private javax.swing.JSpinner spnSeBaja;
    private javax.swing.JSpinner spnSeMedia;
    private javax.swing.JTextField txtLineasPF;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
