/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrOperaciones;
import controlador.Servicios;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JFrame;

/**
 *
 * @author Darwin
 */
public class FactorEscalaFrame extends javax.swing.JFrame {

    /**
     * Creates new form FactorEscalaFrame
     */
    Servicios sv = new Servicios();
    BigDecimal bigDecimal;

    JFrame ventana = new JFrame("Factor Escalar");

    public FactorEscalaFrame() {
        initComponents();
        jPanel1.setBackground(PrincipalFrame.color1);
        this.getContentPane().setBackground(PrincipalFrame.color2);
        bigDecimal = new BigDecimal(CtrOperaciones.est.getFactorEscala()).setScale(2, RoundingMode.UP);
        lbEscala.setText(String.valueOf(bigDecimal));
        this.setResizable(false);
        txtMessage.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEscala = new javax.swing.JLabel();
        cbxPrecedencia = new javax.swing.JComboBox<>();
        cbxFlexibilidad = new javax.swing.JComboBox<>();
        cbxArquitectura = new javax.swing.JComboBox<>();
        cbxCohesion = new javax.swing.JComboBox<>();
        cbxMadurez = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbEscala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEscala.setText("jLabel8");

        cbxPrecedencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxPrecedencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "HI", "VHI", "XHI", "VLO", "LO" }));
        cbxPrecedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPrecedenciaActionPerformed(evt);
            }
        });

        cbxFlexibilidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxFlexibilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "HI", "VHI", "XHI", "VLO", "LO" }));
        cbxFlexibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFlexibilidadActionPerformed(evt);
            }
        });

        cbxArquitectura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxArquitectura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "HI", "VHI", "XHI", "VLO", "LO" }));
        cbxArquitectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxArquitecturaActionPerformed(evt);
            }
        });

        cbxCohesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxCohesion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "HI", "VHI", "XHI", "VLO", "LO" }));
        cbxCohesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCohesionActionPerformed(evt);
            }
        });

        cbxMadurez.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxMadurez.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOM", "HI", "VHI", "XHI", "VLO", "LO" }));
        cbxMadurez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMadurezActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Precedencia");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Flexibilidad");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Arquitectura / Resolución de riesgo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cohesión de equipo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Madurez del Proceso");

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Factor Escala");

        txtMessage.setEditable(false);
        txtMessage.setBackground(new java.awt.Color(36, 41, 46));
        txtMessage.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        txtMessage.setForeground(new java.awt.Color(204, 204, 204));
        txtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMessage.setText("FACTOR ESCALA");
        txtMessage.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxArquitectura, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxPrecedencia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxFlexibilidad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbxCohesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMadurez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEscala))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxPrecedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxFlexibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxArquitectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxCohesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxMadurez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbEscala))
                .addGap(32, 32, 32)
                .addComponent(btnOk)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPrecedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPrecedenciaActionPerformed
        // TODO add your handling code here:
        if ("NOM" == cbxPrecedencia.getSelectedItem()) {
            CtrOperaciones.array[0] = 3.72;
        }
        if ("HI" == cbxPrecedencia.getSelectedItem()) {
            CtrOperaciones.array[0] = 2.48;
        }
        if ("VHI" == cbxPrecedencia.getSelectedItem()) {
            CtrOperaciones.array[0] = 1.24;
        }
        if ("XHI" == cbxPrecedencia.getSelectedItem()) {
            CtrOperaciones.array[0] = 0.0;
        }
        if ("VLO" == cbxPrecedencia.getSelectedItem()) {
            CtrOperaciones.array[0] = 6.20;
        }
        if ("LO" == cbxPrecedencia.getSelectedItem()) {
            CtrOperaciones.array[6] = 4.96;
        }
        
        bigDecimal = new BigDecimal(sv.calFactorEscala()).setScale(2, RoundingMode.UP);
        lbEscala.setText(String.valueOf(bigDecimal));
    }//GEN-LAST:event_cbxPrecedenciaActionPerformed

    private void cbxFlexibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFlexibilidadActionPerformed
        // TODO add your handling code here:
        if ("NOM" == cbxFlexibilidad.getSelectedItem()) {
            CtrOperaciones.array[1] = 3.04;
        }
        if ("HI" == cbxFlexibilidad.getSelectedItem()) {
            CtrOperaciones.array[1] = 2.03;
        }
        if ("VHI" == cbxFlexibilidad.getSelectedItem()) {
            CtrOperaciones.array[1] = 1.01;
        }
        if ("XHI" == cbxFlexibilidad.getSelectedItem()) {
            CtrOperaciones.array[1] = 0.0;
        }
        if ("VLO" == cbxFlexibilidad.getSelectedItem()) {
            CtrOperaciones.array[1] = 5.07;
        }
        if ("LO" == cbxFlexibilidad.getSelectedItem()) {
            CtrOperaciones.array[1] = 4.05;
        }
        bigDecimal = new BigDecimal(sv.calFactorEscala()).setScale(2, RoundingMode.UP);
        lbEscala.setText(String.valueOf(bigDecimal));
        //lbEscala.setText(String.valueOf(formato1.format(sv.calFactorEscala())));
    }//GEN-LAST:event_cbxFlexibilidadActionPerformed

    private void cbxArquitecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxArquitecturaActionPerformed
        // TODO add your handling code here:
        if ("NOM" == cbxArquitectura.getSelectedItem()) {
            CtrOperaciones.array[2] = 4.24;
        }
        if ("HI" == cbxArquitectura.getSelectedItem()) {
            CtrOperaciones.array[2] = 2.83;
        }
        if ("VHI" == cbxArquitectura.getSelectedItem()) {
            CtrOperaciones.array[2] = 1.41;
        }
        if ("XHI" == cbxArquitectura.getSelectedItem()) {
            CtrOperaciones.array[2] = 0.0;
        }
        if ("VLO" == cbxArquitectura.getSelectedItem()) {
            CtrOperaciones.array[2] = 7.0;
        }
        if ("LO" == cbxArquitectura.getSelectedItem()) {
            CtrOperaciones.array[2] = 5.65;
        }
        bigDecimal = new BigDecimal(sv.calFactorEscala()).setScale(2, RoundingMode.UP);
        lbEscala.setText(String.valueOf(bigDecimal));
        //lbEscala.setText(String.valueOf(formato1.format(sv.calFactorEscala())));
    }//GEN-LAST:event_cbxArquitecturaActionPerformed

    private void cbxCohesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCohesionActionPerformed
        // TODO add your handling code here:
        if ("NOM" == cbxCohesion.getSelectedItem()) {
            CtrOperaciones.array[3] = 3.29;
        }
        if ("HI" == cbxCohesion.getSelectedItem()) {
            CtrOperaciones.array[3] = 2.19;
        }
        if ("VHI" == cbxCohesion.getSelectedItem()) {
            CtrOperaciones.array[3] = 1.10;
        }
        if ("XHI" == cbxCohesion.getSelectedItem()) {
            CtrOperaciones.array[3] = 0.0;
        }
        if ("VLO" == cbxCohesion.getSelectedItem()) {
            CtrOperaciones.array[3] = 5.48;
        }
        if ("LO" == cbxCohesion.getSelectedItem()) {
            CtrOperaciones.array[3] = 4.38;
        }
        bigDecimal = new BigDecimal(sv.calFactorEscala()).setScale(2, RoundingMode.UP);
        lbEscala.setText(String.valueOf(bigDecimal));
       // lbEscala.setText(String.valueOf(formato1.format(sv.calFactorEscala())));
    }//GEN-LAST:event_cbxCohesionActionPerformed

    private void cbxMadurezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMadurezActionPerformed
        // TODO add your handling code here:
        if ("NOM" == cbxMadurez.getSelectedItem()) {
            CtrOperaciones.array[4] = 4.68;
        }
        if ("HI" == cbxMadurez.getSelectedItem()) {
            CtrOperaciones.array[4] = 3.12;
        }
        if ("VHI" == cbxMadurez.getSelectedItem()) {
            CtrOperaciones.array[4] = 1.56;
        }
        if ("XHI" == cbxMadurez.getSelectedItem()) {
            CtrOperaciones.array[4] = 0.0;
        }
        if ("VLO" == cbxMadurez.getSelectedItem()) {
            CtrOperaciones.array[4] = 7.80;
        }
        if ("LO" == cbxMadurez.getSelectedItem()) {
            CtrOperaciones.array[4] = 6.24;
        }
        bigDecimal = new BigDecimal(sv.calFactorEscala()).setScale(2, RoundingMode.UP);
        lbEscala.setText(String.valueOf(bigDecimal));
        //lbEscala.setText(String.valueOf(formato1.format(sv.calFactorEscala())));
    }//GEN-LAST:event_cbxMadurezActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    //  int cont = 1;    int contF = 1;     int contA = 1;   int contC = 1;    int contM = 1;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactorEscalaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactorEscalaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactorEscalaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactorEscalaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactorEscalaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbxArquitectura;
    private javax.swing.JComboBox<String> cbxCohesion;
    private javax.swing.JComboBox<String> cbxFlexibilidad;
    private javax.swing.JComboBox<String> cbxMadurez;
    private javax.swing.JComboBox<String> cbxPrecedencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbEscala;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
