/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrOperaciones;
import controlador.Servicios;
import java.text.DecimalFormat;
import javax.swing.JFrame;



/**
 *
 * @author Darwin
 */
public class MulEsfuerzoFrame extends javax.swing.JFrame {

    /**
     * Creates new form MulEsfuerzoFrame
     */
    DecimalFormat formato1 = new DecimalFormat("#.00");
    Servicios sv = new Servicios();

    JFrame ventana = new JFrame("Multiplicador Esfuerzo");

    public MulEsfuerzoFrame() {
        initComponents();
        lbMulti.setText(String.valueOf(CtrOperaciones.est.getMulEsfuerzo()));
        ventana.setSize(800, 600);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        txtMessage.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnComplejidad = new javax.swing.JButton();
        btnReusabilidad = new javax.swing.JButton();
        btnPlataforma = new javax.swing.JButton();
        btnAptitud = new javax.swing.JButton();
        btnExperiencia = new javax.swing.JButton();
        btnFacilidades = new javax.swing.JButton();
        btnCronograma = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbMulti = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Confiabilidad y Complejidad");

        jLabel5.setText("Experiendia del Personal");

        jLabel2.setText("Reusabilidad Requerida");

        jLabel3.setText("Dificultad de la Plataforma");

        jLabel4.setText("Aptitud del Personal");

        btnComplejidad.setText("NOM");
        btnComplejidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplejidadActionPerformed(evt);
            }
        });

        btnReusabilidad.setText("NOM");
        btnReusabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReusabilidadActionPerformed(evt);
            }
        });

        btnPlataforma.setText("NOM");
        btnPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlataformaActionPerformed(evt);
            }
        });

        btnAptitud.setText("NOM");
        btnAptitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAptitudActionPerformed(evt);
            }
        });

        btnExperiencia.setText("NOM");
        btnExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExperienciaActionPerformed(evt);
            }
        });

        btnFacilidades.setText("NOM");
        btnFacilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilidadesActionPerformed(evt);
            }
        });

        btnCronograma.setText("NOM");
        btnCronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCronogramaActionPerformed(evt);
            }
        });

        jLabel6.setText("Facilidades");

        jLabel7.setText("Cronograma de desarrollo Requerido");

        jButton1.setText("Cancelar");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel8.setText("Total: ");

        lbMulti.setText("jLabel9");

        txtMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMessage.setText("Multiplicador Esfuerzo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbMulti)
                                    .addComponent(btnFacilidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCronograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAptitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReusabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnComplejidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComplejidad)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReusabilidad)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlataforma)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnAptitud))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnExperiencia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnFacilidades))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnCronograma))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbMulti))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnOk))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int cont = 1;
    private void btnComplejidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplejidadActionPerformed
       if (cont < 7) {
            cont++;
        } else {
            cont = 1;
        }

        switch (cont) {
            case 1:
                btnComplejidad.setText("NOM");
                CtrOperaciones.arrayM[0] = 1;
                break;
            case 2:
                btnComplejidad.setText("HI");
                CtrOperaciones.arrayM[0] = 1.3;
                break;
            case 3:
                btnComplejidad.setText("VHI");
                CtrOperaciones.arrayM[0] = 1.74;
                break;
            case 4:
                btnComplejidad.setText("XHI");
                CtrOperaciones.arrayM[0] = 2.38;
                break;
            case 5:
                btnComplejidad.setText("XLO");
                CtrOperaciones.arrayM[0] = 0.73;
                break;
            case 6:
                btnComplejidad.setText("VLO");
                CtrOperaciones.arrayM[0] = 0.81;
                break;
            case 7:
                btnComplejidad.setText("LO");
                CtrOperaciones.arrayM[0] = 0.98;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));
    }//GEN-LAST:event_btnComplejidadActionPerformed
    int conR = 1;
    private void btnReusabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReusabilidadActionPerformed
         if (conR < 7) {
            conR++;
        } else {
            conR = 1;
        }

        switch (conR) {
            case 1:
                btnReusabilidad.setText("NOM");
                CtrOperaciones.arrayM[1] = 1;
                break;
            case 2:
                btnReusabilidad.setText("HI");
                CtrOperaciones.arrayM[1] = 1.07;
                break;
            case 3:
                btnReusabilidad.setText("VHI");
                CtrOperaciones.arrayM[1] = 1.15;
                break;
            case 4:
                btnReusabilidad.setText("XHI");
                CtrOperaciones.arrayM[1] = 1.24;
                break;
            case 5:
                btnReusabilidad.setText("XLO");
                CtrOperaciones.arrayM[1] = 1;
                break;
            case 6:
                btnReusabilidad.setText("VLO");
                CtrOperaciones.arrayM[1] = 1;
                break;
            case 7:
                btnReusabilidad.setText("LO");
                CtrOperaciones.arrayM[1] = 0.95;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));
    }//GEN-LAST:event_btnReusabilidadActionPerformed
int conP = 1;
    private void btnPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlataformaActionPerformed
       if (conP < 7) {
            conP++;
        } else {
            conP = 1;
        }
        switch (conP) {
            case 1:
                btnPlataforma.setText("NOM");
                CtrOperaciones.arrayM[2] = 1;
                break;
            case 2:
                btnPlataforma.setText("HI");
                CtrOperaciones.arrayM[2] = 1.29;
                break;
            case 3:
                btnPlataforma.setText("VHI");
                CtrOperaciones.arrayM[2] = 1.81;
                break;
            case 4:
                btnPlataforma.setText("XHI");
                CtrOperaciones.arrayM[2] = 2.61;
                break;
            case 5:
                btnPlataforma.setText("XLO");
                CtrOperaciones.arrayM[2] = 1;
                break;
            case 6:
                btnPlataforma.setText("VLO");
                CtrOperaciones.arrayM[2] = 1;
                break;
            case 7:
                btnPlataforma.setText("LO");
                CtrOperaciones.arrayM[2] = 0.87;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));  
    }//GEN-LAST:event_btnPlataformaActionPerformed
int conA = 1;
    private void btnAptitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAptitudActionPerformed
         if (conA < 7) {
            conA++;
        } else {
            conA = 1;
        }
        switch (conA) {
            case 1:
                btnAptitud.setText("NOM");
                CtrOperaciones.arrayM[3] = 1;
                break;
            case 2:
                btnAptitud.setText("HI");
                CtrOperaciones.arrayM[3] = 0.83;
                break;
            case 3:
                btnAptitud.setText("VHI");
                CtrOperaciones.arrayM[3] = 0.63;
                break;
            case 4:
                btnAptitud.setText("XHI");
                CtrOperaciones.arrayM[3] = 0.5;
                break;
            case 5:
                btnAptitud.setText("XLO");
                CtrOperaciones.arrayM[3] = 2.12;
                break;
            case 6:
                btnAptitud.setText("VLO");
                CtrOperaciones.arrayM[3] = 1.62;
                break;
            case 7:
                btnAptitud.setText("LO");
                CtrOperaciones.arrayM[3] = 1.26;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));
    }//GEN-LAST:event_btnAptitudActionPerformed
int conE = 1;
    private void btnExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExperienciaActionPerformed
         if (conE < 7) {
            conE++;
        } else {
            conE = 1;
        }
        switch (conE) {
            case 1:
                btnExperiencia.setText("NOM");
                CtrOperaciones.arrayM[4] = 1;
                break;
            case 2:
                btnExperiencia.setText("HI");
                CtrOperaciones.arrayM[4] = 0.87;
                break;
            case 3:
                btnExperiencia.setText("VHI");
                CtrOperaciones.arrayM[4] = 0.71;
                break;
            case 4:
                btnExperiencia.setText("XHI");
                CtrOperaciones.arrayM[4] = 0.62;
                break;
            case 5:
                btnExperiencia.setText("XLO");
                CtrOperaciones.arrayM[4] = 1.59;
                break;
            case 6:
                btnExperiencia.setText("VLO");
                CtrOperaciones.arrayM[4] = 1.33;
                break;
            case 7:
                btnExperiencia.setText("LO");
                CtrOperaciones.arrayM[4] = 1.12;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));
    }//GEN-LAST:event_btnExperienciaActionPerformed
   int conF = 1;
    private void btnFacilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilidadesActionPerformed
         if (conF < 7) {
            conF++;
        } else {
            conF = 1;
        }
        switch (conF) {
            case 1:
                btnFacilidades.setText("NOM");
                CtrOperaciones.arrayM[5] = 1;
                break;
            case 2:
                btnFacilidades.setText("HI");
                CtrOperaciones.arrayM[5] = 0.87;
                break;
            case 3:
                btnFacilidades.setText("VHI");
                CtrOperaciones.arrayM[5] = 0.73;
                break;
            case 4:
                btnFacilidades.setText("XHI");
                CtrOperaciones.arrayM[5] = 0.62;
                break;
            case 5:
                btnFacilidades.setText("XHI");
                CtrOperaciones.arrayM[5] = 1.43;
                break;
            case 6:
                btnFacilidades.setText("VLO");
                CtrOperaciones.arrayM[5] = 1.3;
                break;
            case 7:
                btnFacilidades.setText("LO");
                CtrOperaciones.arrayM[5] = 1.1;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));
    }//GEN-LAST:event_btnFacilidadesActionPerformed
    int contC = 1;
    private void btnCronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCronogramaActionPerformed
        // TODO add your handling code here:
        if (contC < 7) {
            contC++;
        } else {
            contC = 1;
        }
        switch (contC) {
            case 1:
                btnCronograma.setText("NOM");
                CtrOperaciones.arrayM[6] = 1;
                break;
            case 2:
                btnCronograma.setText("HI");
                CtrOperaciones.arrayM[6] = 1;
                break;
            case 3:
                btnCronograma.setText("VHI");
                CtrOperaciones.arrayM[6] = 1;
                break;
            case 4:
                btnCronograma.setText("XHI");
                CtrOperaciones.arrayM[6] = 1;
                break;
            case 5:
                btnCronograma.setText("XHI");
                CtrOperaciones.arrayM[6] = 1;
                break;
            case 6:
                btnCronograma.setText("VLO");
                CtrOperaciones.arrayM[6] = 1.43;
                break;
            case 7:
                btnCronograma.setText("LO");
                CtrOperaciones.arrayM[6] = 1.14;
                break;
        }
        lbMulti.setText(String.valueOf(formato1.format(sv.calMultiEsfuerzo())));
    }//GEN-LAST:event_btnCronogramaActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MulEsfuerzoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MulEsfuerzoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MulEsfuerzoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MulEsfuerzoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MulEsfuerzoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAptitud;
    private javax.swing.JButton btnComplejidad;
    private javax.swing.JButton btnCronograma;
    private javax.swing.JButton btnExperiencia;
    private javax.swing.JButton btnFacilidades;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPlataforma;
    private javax.swing.JButton btnReusabilidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbMulti;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
