/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Servicios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darwin
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    Servicios sv = new Servicios();
    //Estimacion est = new Estimacion();

    DefaultTableModel model = new DefaultTableModel();

    public PrincipalFrame() {
        initComponents();
        JOptionPane.showMessageDialog(null, "En caso de no ingresar Valores se usaran valores por defecto", "Mensaje Informativo", JOptionPane.INFORMATION_MESSAGE);
        txtNombre.requestFocus();
        txtSced.setText("25");
        txtCost.setText("10");
        txtSalario.setText("0");
        txtNombre.setText("<Sample>");
        model.addColumn("Nombre");
        model.addColumn("Punto Función");
        model.addColumn("Lineas Cod");
        //model.addColumn("Factor Escala");
        //  model.addColumn("Esf. Nominal");
        //model.addColumn("Mul. Esfuezo");
        model.addColumn("Esf. Estimado");
        model.addColumn("Est. Tiempo");
        model.addColumn("% Holgura");
        model.addColumn("Tiempo Total");
        model.addColumn("Est. Persona");
        model.addColumn("Pago hora");
        model.addColumn("Est. Costo");
        model.addColumn("% Extra Costo");
        model.addColumn("Costo Total");
        this.jtTable.setModel(model);
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        txtSced = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnReestrablecer = new javax.swing.JButton();
        btnFactor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMultiplicador = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTable = new javax.swing.JTable();
        txtCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtSced.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setText("Nombre del Proyecto: ");

        btnAgregar.setText("Punto Funcion");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Porcentaje de variación del Calendario: ");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnReestrablecer.setText("Restablecer");
        btnReestrablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestrablecerActionPerformed(evt);
            }
        });

        btnFactor.setText("Factor Escala");
        btnFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorActionPerformed(evt);
            }
        });

        jLabel3.setText("Salario por Hora: ");

        btnMultiplicador.setText("Multiplicador Esfuerzo");
        btnMultiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicadorActionPerformed(evt);
            }
        });

        jLabel4.setText("Porcentaje variación del Costo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtTable.setForeground(new java.awt.Color(51, 51, 51));
        jtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Punto Función", "Lineas de Codigo", "Esfuerzo Estimado", "Est. tiempo", "% Holgura", "Tiempo Total", "Est. Personal", "Pago Hora", "Est. Costo", "% Extra Costo", "Costo Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSced, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(429, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReestrablecer)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFactor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMultiplicador)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnMultiplicador)
                    .addComponent(btnFactor)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReestrablecer)
                    .addComponent(btnCalcular)
                    .addComponent(btnEliminar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int eli = jtTable.getSelectedRowCount();
        if (eli >= 0) {
            model.removeRow(eli);
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos que eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AgregarFrame ag = new AgregarFrame();
        ag.show();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
if (sv.est.getLineasCod() == 0) {
            int op = JOptionPane.showConfirmDialog(null, "Las Lineas de Codigo son 0, Desea Continuar");
            if (JOptionPane.OK_OPTION == op) {
                double sced = Double.parseDouble(txtSced.getText());
                double salario = Double.parseDouble(txtSalario.getText());
                double costV = Double.parseDouble(txtCost.getText());
                sv.calcularPmEstimado();
                sv.calcularEstTiempo(sced);
                sv.calcularEstPersona();
                sv.calcularEstCosto(salario, costV);
                String[] agregar = new String[12];
                agregar[0] = txtNombre.getText();
                agregar[1] = String.valueOf(sv.est.getPuntoFuncion());
                agregar[2] = String.valueOf(sv.est.getLineasCod() * 1000);
                //agregar[3] = String.valueOf(sv.est.getFactorEscala());
                //agregar[4] = String.valueOf(sv.est.getPmNominal());
                //agregar[5] = String.valueOf(sv.est.getMulEsfuerzo());
                agregar[3] = String.valueOf(sv.est.getPmEstimado());
                agregar[4] = String.valueOf(sv.est.getEstTiempo() / (1 + (sced * 0.01)));
                agregar[5] = String.valueOf(sced);
                agregar[6] = String.valueOf(sv.est.getEstTiempo());
                agregar[7] = String.valueOf(sv.est.getEsthHombre());
                agregar[8] = String.valueOf(salario);
                agregar[9] = String.valueOf(sv.est.getEstCosto() / (1 + (costV * 0.01)));
                agregar[10] = String.valueOf(costV);
                agregar[11] = String.valueOf(sv.est.getEstCosto());
                model.addRow(agregar);
            }
        } else {
            double sced = Double.parseDouble(txtSced.getText());
            double salario = Double.parseDouble(txtSalario.getText());
            double costV = Double.parseDouble(txtCost.getText());
            sv.calcularPmEstimado();
            sv.calcularEstTiempo(sced);
            sv.calcularEstPersona();
            sv.calcularEstCosto(salario, costV);
            String[] agregar = new String[12];
            agregar[0] = txtNombre.getText();
            agregar[1] = String.valueOf(sv.est.getPuntoFuncion());
            agregar[2] = String.valueOf(sv.est.getLineasCod() * 1000);
            // agregar[3] = String.valueOf(sv.est.getFactorEscala());
            //agregar[4] = String.valueOf(sv.est.getPmNominal());
            //agregar[5] = String.valueOf(sv.est.getMulEsfuerzo());
            agregar[3] = String.valueOf(sv.est.getPmEstimado());
            agregar[4] = String.valueOf(sv.est.getEstTiempo() / (1 + (sced * 0.01)));
            agregar[5] = String.valueOf(sced);
            agregar[6] = String.valueOf(sv.est.getEstTiempo());
            agregar[7] = String.valueOf(sv.est.getEsthHombre());
            agregar[8] = String.valueOf(salario);
            agregar[9] = String.valueOf(sv.est.getEstCosto() / (1 + (costV * 0.01)));
            agregar[10] = String.valueOf(costV);
            agregar[11] = String.valueOf(sv.est.getEstCosto());
            model.addRow(agregar);
        }
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnReestrablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestrablecerActionPerformed
        // TODO add your handling code here:
        int eliT = jtTable.getRowCount();
        for (int i = eliT - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnReestrablecerActionPerformed

    private void btnFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorActionPerformed
        // TODO add your handling code here:
        FactorEscalaFrame fe = new FactorEscalaFrame();
        fe.show();
    }//GEN-LAST:event_btnFactorActionPerformed

    private void btnMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicadorActionPerformed
        // TODO add your handling code here:
        MulEsfuerzoFrame mf = new MulEsfuerzoFrame();
        mf.show();
    }//GEN-LAST:event_btnMultiplicadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFactor;
    private javax.swing.JButton btnMultiplicador;
    private javax.swing.JButton btnReestrablecer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTable;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSced;
    // End of variables declaration//GEN-END:variables
}
